cameras:
- camera:
    distortion:
      parameters:
        cols: 1
        rows: 4
        data: [0.0, 0.0, 0.0, 0.0]
      type: radial-tangential
    image_height: 480
    image_width: 640
    intrinsics:
      cols: 1
      rows: 4
      data: [428.0, 428.0, 320.0, 240.0]
      label: /left_grayscale/image
    line-delay-nanoseconds: 0
    type: pinhole
  T_B_C:
    cols: 4
    rows: 4
    data: [0.99984983, -0.00373198,  0.01692284,  -0.074783895,
           0.00403133,  0.9998354 , -0.01768969,  -0.0005     ,
          -0.01685403,  0.01775525,  0.9997003 ,  -0.0041,
           0.        ,  0.        ,  0.        ,  1.        ]
  serial_no: 0
  calib_date: 0
  description: 'left cam'
- camera:
    distortion:
      parameters:
        cols: 1
        rows: 4
        data: [0.0, 0.0, 0.0, 0.0]
      type: radial-tangential
    image_height: 480
    image_width: 640
    intrinsics:
      cols: 1
      rows: 4
      data: [428.0, 428.0, 320.0, 240.0]
    label: /right_grayscale/image
    line-delay-nanoseconds: 0
    type: pinhole
  T_B_C:
    cols: 4
    rows: 4
    data: [0.99746136, -0.00394329, -0.07110054, 0.074783895,
           0.00236645,  0.99974967, -0.02224833, 0.0005,
           0.07117047,  0.02202359,  0.997221  , 0.0041,
           0.        ,  0.        ,  0.        ,  1.       ]
  serial_no: 0
  calib_date: 0
  description: 'right cam'
label: slamdunk_forward_stereo

imu_params:
  delay_imu_cam: 0.0
  max_imu_delta_t: 0.01
  acc_max: 176.0
  omega_max: 7.8
  sigma_omega_c: 0.005
  sigma_acc_c: 0.01
  sigma_omega_bias_c: 4.0e-6
  sigma_acc_bias_c: 0.0002
  sigma_integration: 0.0
  g: 9.81007
  imu_rate: 200.0

imu_initialization:
  velocity: [0, 0, 0]
  omega_bias: [0, 0, 0]
  acc_bias: [0, 0, 0]
  velocity_sigma: 0.5
  omega_bias_sigma: 0.005
  acc_bias_sigma: 0.05
